version: "3.2"
services:
     refapp-db:
         build:
             context: ./mysql
         container_name: refapp-db
         ports:
             - "3320:3306"
         networks:
             - network
         volumes:
             - datadb:/var/lib/mysql
             
     refapp-tomcat:
         build:
             context: ./tomcat
         container_name: refapp-tomcat
         ports:
             - "8080:8080"
             - "465:465"
         networks:
             - network
         depends_on:
             - "refapp-db"
         environment:
             DISA_ENVIRONMENT:
             DISA_API_USERNAME:
             DISA_API_PASSWORD:
         volumes:
           - type: bind
             source: ./data/webapps
             target: /usr/local/tomcat/webapps
           - type: bind
             source: ./data/OpenMRS
             target: /usr/local/tomcat/.OpenMRS
           - type: bind
             source: ./data/logs
             target: /usr/local/tomcat/logs
         healthcheck:
            test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
            interval: 2s
            timeout: 30s
            retries: 15
networks:
  network:
    driver: bridge

volumes:
  datadb:
