version: "3.2"
services:
    refapp-db:
        build:
            context: ./mysql
        container_name: refapp-db
        ports:
            - "3320:3306"
        networks:
            - network
        volumes:
            - datadb:/var/lib/mysql
        restart: unless-stopped
    refapp-tomcat:
        build:
            context: ./tomcat
        container_name: refapp-tomcat
        ports:
            - "465:465"
            - "8002:8002"
        networks:
            - network
        depends_on:
            - "refapp-db"
        volumes:
          - type: bind
            source: ./data/webapps
            target: /usr/local/tomcat/webapps
          - type: bind
            source: ./data/OpenMRS
            target: /usr/local/tomcat/.OpenMRS
          - type: bind
            source: ./data/logs
            target: /usr/local/tomcat/logs
        healthcheck:
          test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
          interval: 2s
          timeout: 30s
          retries: 15
        restart: unless-stopped
networks:
  network:
    driver: bridge

volumes:
  datadb:
