version: "3.2"
services:
     refapp-db:
         build:
             context: ./mysql
         container_name: refapp-db
         ports:
             - "3320:3306"
         networks:
             - network
         volumes:
             - datadb:/var/lib/mysql
             
     refapp-tomcat:
         build:
             context: ./tomcat
         container_name: refapp-tomcat
         ports:
             - "8080:8080"
         networks:
             - network
         depends_on:
             - "refapp-db"
         volumes:
           - type: bind
             source: ./data/webapps
             target: /usr/local/tomcat/webapps
           - type: bind
             source: ./data/OpenMRS
             target: /usr/local/tomcat/.OpenMRS
           - type: bind
             source: ./data/logs
             target: /usr/local/tomcat/logs
         healthcheck:
            test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
            interval: 2s
            timeout: 30s
            retries: 15

     openmrs-eip-sender:
       image: openjdk:17-alpine
       command: /home/eip/scripts/install.sh
       container_name: openmrs-eip-sender
       network_mode: host
       environment:
         - curr_git_branch=main
       env_file:
         - ./dbsync/eip.env
       working_dir: /home/eip
       volumes:
         - /etc/timezone:/etc/timezone:ro
         - /etc/localtime:/etc/localtime:ro
         - ./dbsync/install.sh:/home/eip/scripts/install.sh
         - ./dbsync/:/home/openmrs-eip-docker
         - ./data/shared:/home/eip/shared
       restart: unless-stopped


networks:
  network:
    driver: bridge

volumes:
  datadb:
