version: "3.2"
services:
    gateway:
        image: openmrs/openmrs-reference-application-3-gateway:3.0.0-beta.13
        restart: "unless-stopped"
        depends_on:
          - frontend
          - backend
        ports:
          - "80:80"
        networks:
          - network
    frontend:
      image: openmrs/openmrs-reference-application-3-frontend:3.0.0-beta.13
      restart: "unless-stopped"
      environment:
        SPA_PATH: /openmrs/spa
        API_URL: /openmrs
        SPA_CONFIG_URLS:
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost/"]
        timeout: 5s
      depends_on:
        - backend
      networks:
        - network
    refapp-db:
        build:
            context: ./mysql
        container_name: refapp-db
        ports:
            - "3320:3306"
        networks:
            - network
        volumes:
            - datadb:/var/lib/mysql
        restart: unless-stopped
    backend:
        build:
            context: ./tomcat
        container_name: backend
        ports:
            - "465:465"
            - "8002:8002"
        networks:
            - network
        depends_on:
            - "refapp-db"
        environment:
             DISA_ENVIRONMENT:
             DISA_API_USERNAME:
             DISA_API_PASSWORD:
        volumes:
          - type: bind
            source: ./data/webapps
            target: /usr/local/tomcat/webapps
          - type: bind
            source: ./data/OpenMRS
            target: /usr/local/tomcat/.OpenMRS
          - type: bind
            source: ./data/logs
            target: /usr/local/tomcat/logs
        healthcheck:
          test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
          interval: 2s
          timeout: 30s
          retries: 15
        restart: unless-stopped
networks:
  network:
    driver: bridge

volumes:
  datadb:
